export const FETCH_SOUNDS = "FETCH_SOUNDS"
export const FETCH_SOUNDS_START = "FETCH_SOUNDS_START"
export const FETCH_SOUNDS_SUCCESS = "FETCH_SOUNDS_SUCCESS"
export const FETCH_SOUNDS_FAIL = "FETCH_SOUNDS_FAIL"
